// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ7AOkJwzP0y1qHVq8x_1Mbi8dysxgN0U',
    appId: '1:97059560983:web:3090342445a831e8b34652',
    messagingSenderId: '97059560983',
    projectId: 'campus-buddy-1558',
    authDomain: 'campus-buddy-1558.firebaseapp.com',
    storageBucket: 'campus-buddy-1558.firebasestorage.app',
    measurementId: 'G-CDBX8EMHJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLDySDQ57ya0nFBo15DkBOMbQmkRDf6dg',
    appId: '1:97059560983:android:2fe24c3f7c7ae76cb34652',
    messagingSenderId: '97059560983',
    projectId: 'campus-buddy-1558',
    storageBucket: 'campus-buddy-1558.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5IVLFpCqrUS_y96IwSJGCr10jBAqSSo4',
    appId: '1:97059560983:ios:7a1512c5f7099c7db34652',
    messagingSenderId: '97059560983',
    projectId: 'campus-buddy-1558',
    storageBucket: 'campus-buddy-1558.firebasestorage.app',
    iosBundleId: 'com.example.campusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5IVLFpCqrUS_y96IwSJGCr10jBAqSSo4',
    appId: '1:97059560983:ios:7a1512c5f7099c7db34652',
    messagingSenderId: '97059560983',
    projectId: 'campus-buddy-1558',
    storageBucket: 'campus-buddy-1558.firebasestorage.app',
    iosBundleId: 'com.example.campusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ7AOkJwzP0y1qHVq8x_1Mbi8dysxgN0U',
    appId: '1:97059560983:web:b46e0f8d57cb3c5db34652',
    messagingSenderId: '97059560983',
    projectId: 'campus-buddy-1558',
    authDomain: 'campus-buddy-1558.firebaseapp.com',
    storageBucket: 'campus-buddy-1558.firebasestorage.app',
    measurementId: 'G-JYHZLDT2VP',
  );
}
